spring.application.name=hrm-backend

# ===== MySQL =====
spring.datasource.url=jdbc:mysql://localhost:3306/hrm_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== JWT =====
# Chuoi bi mat >= 32 ky tu (Base64). Doi thanh chuoi rieng cua ban.
app.jwt.secret=ZHVuZ2Rob2FuZ2JpbWF0MzJraXR1Y2hvaHJtc3lzdGVtMjAyNg==
# 30 phut = 1800000 ms (idle timeout - frontend tu refresh khi con hoat dong)
app.jwt.expiration-ms=1800000

# ===== Server =====
server.port=8080

# ===== Upload avatar =====
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# ===== Cloudinary (dien 3 gia tri tu Dashboard Cloudinary) =====
cloudinary.cloud-name=doj9thlet
cloudinary.api-key=562728421816383
cloudinary.api-secret=oKrtakqNa1w0IJWTlQrJIAhXMDI
